### ISSUE TITLE
dates shld be dates

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/cdcfluview#12]
cannot publish to CRAN w/o ensuring all dates in data frames are actual dates.

**Comment by hrbrmstr** [comment]
Hey @craigjmcgowan ! (figured this was the least noisy way to ping you)

I took a dive into the new CDC site and revamped the pkg a tag. Wld you mind taking a peek? I am not an epidemiologist (well, not a human one anyway…I deal with cyber pathogens quite a bit tho) and am not sure I've covered everything or left something important out.

I also completely revamped the pkg API and wld 💙  input on whether it makes sense of if I shld provide helpers that mimic the old functionality.

**Comment by craigjmcgowan** [comment]
@hrbrmstr thanks for reaching out! I'll take a look tonight when I get home. The current functions are working on my work machine right now and I need them for some tasks later today, but I'll update the version on my personal machine and give it a test drive. Appreciate all the work you've put into this - I mostly work on the CDC's [influenza forecasting challenge](https://predict.phiresearchlab.org) and I know many of the participating teams use your tools to access the data.

**Comment by hrbrmstr** [comment]
Thx! I shld have mentioned that I checkpointed a release with your fixes in it — https://github.com/hrbrmstr/cdcfluview/releases/tag/v0.5.2 — so folks can default to that in the interim (I'll dbl check to see if I mentioned that in the README, too).

**Comment by craigjmcgowan** [comment]
Sorry for the delay. I updated to the newest version last night and checked out all of the new functions. Everything ran smoothly and I think that splitting out some of the tasks into individual functions is a great idea and makes it a little clearer as to what exactly each function is doing. I can't think of anything else on the FluView site that could be added as well

My biggest piece of feedback would be that it would be extremely helpful to have arguments for `year=` in those functions that would support it, specifically `age_group_distribution`, `geographic_spread`, `hospitalizations`, `ilinet`, `pi_mortality`, and `who_nrevss`. I know I often only want particular seasons and since that's part of the underlying API hopefully it would be straightforward to implement in the new functions.

Smaller ideas would be including sub location again for `ilinet` similar to the old `get_flu_data` function and maybe allowing for a vector of approved locations in `hospitalizations`, since the API can support multiple regions selected.

As for the old functions - it might be more trouble than it's worth to link the new functions to the old ones. Could you do something similar to what a lot of tidyverse packages do and include the old functions for a certain amount of time, but print a warning when any is used that this function is deprecated and will be eliminated in the next release, with a pointer to the new function? This way existing code doesn't break immediately but its clear to users that they need to update their code soon or it will break in the future.

Thanks again for all of your work on this and let me know if I can help pulling things together.

**Comment by hrbrmstr** [comment]
just a quick update: added a `years` parameter to all the new functions and will work on adding in the deprecated functions and adding a deprecation warning.

**Comment by hrbrmstr** [comment]
Got all the old ported over and even managed to remove the V8 pkg dependency in the process. Deprecation warnings are provided and new + old tests are in the test harness. CRAN checks pass, too.

I'll likely submit to CRAN this week barring error reports from folks.
